import test from 'node:test';
import assert from 'node:assert/strict';
import { dispatch } from '../supabase/functions/_shared/domain.mjs';
import { seed } from '../supabase/functions/_shared/seed.mjs';
const admin={admin:true,pepper:'composition-secret',client:'admin'};
const guest={...admin,admin:false,client:'guest'};
async function fixture(){const state=seed();await dispatch(state,'catalog',{},guest);const c1=await dispatch(state,'admin.saveCategory',{title:'КоАП'},admin),c2=await dispatch(state,'admin.saveCategory',{title:'Устав'},admin);for(let i=0;i<8;i++)await dispatch(state,'admin.saveQuestion',{id:`koap${i}`,categoryId:c1.id,text:`КоАП ${i}`,options:['Да','Нет'],correct:0},admin);await dispatch(state,'admin.saveQuestion',{id:'charter1',categoryId:c2.id,text:'Устав',options:['Да','Нет'],correct:0},admin);return {state,c1,c2};}
const exam=blocks=>({type:'exam',title:'Смешанный экзамен',blocks,questionCount:5,timeLimit:10,passingScore:70,published:true,code:'TEST-CODE',departments:['academy']});
const admission=id=>({assessmentId:id,department:'academy',code:'TEST-CODE',fullName:'Проверка',rank:'Рядовой',certificate:'123-456'});
test('legacy themes migrate to stable categories and category renaming keeps questions',async()=>{const state=seed();let data=await dispatch(state,'admin.data',{},admin);assert.equal(data.categories.length,1);const id=data.categories[0].id;await dispatch(state,'admin.saveCategory',{id,title:'Новая тема'},admin);data=await dispatch(state,'admin.data',{},admin);assert.ok(data.questions.every(q=>q.categoryId===id&&q.topic==='Новая тема'));await assert.rejects(dispatch(state,'admin.saveCategory',{title:'Новая тема'},admin),/уже существует/);await assert.rejects(dispatch(state,'admin.saveCategory',{title:'Взлом'},guest),e=>e.status===401);});
test('each attempt samples exactly four unique questions from eight plus one manual question, and shuffles order',async()=>{const {state,c1,c2}=await fixture();const {id}=await dispatch(state,'admin.saveAssessment',exam([{categoryId:c1.id,mode:'random',count:4},{categoryId:c2.id,mode:'manual',questionIds:['charter1']}]),admin);const orders=new Set(),samples=new Set();for(let i=0;i<12;i++){const start=await dispatch(state,'attempt.start',admission(id),{...guest,client:`guest${i}`});const ids=start.attempt.questions.map(q=>q.id);assert.equal(ids.length,5);assert.equal(new Set(ids).size,5);assert.equal(ids.filter(id=>id.startsWith('koap')).length,4);assert.ok(ids.includes('charter1'));orders.add(ids.join(','));samples.add(ids.filter(id=>id.startsWith('koap')).sort().join(','));assert.ok(start.attempt.questions.every(q=>!('correct'in q)));}assert.ok(orders.size>1);assert.ok(samples.size>1);});
test('invalid block quotas, mixed-topic tests and duplicate categories are rejected',async()=>{const {state,c1,c2}=await fixture();const block={categoryId:c1.id,mode:'random',count:4};await assert.rejects(dispatch(state,'admin.saveAssessment',exam([{...block,count:9}]),admin),/число случайных/);await assert.rejects(dispatch(state,'admin.saveAssessment',exam([block,block]),admin),/без повторений/);await assert.rejects(dispatch(state,'admin.saveAssessment',{...exam([block,{categoryId:c2.id,mode:'manual',questionIds:['charter1']}]),type:'test'},admin),/одной категории/);await assert.rejects(dispatch(state,'admin.saveAssessment',exam([{categoryId:c1.id,mode:'manual',questionIds:['charter1']}]),admin),/соответствующей категории/);});
test('generated codes persist for admin only and regenerate only when saved',async()=>{const {state,c1}=await fixture();const {code}=await dispatch(state,'admin.generateCode',{},admin);assert.match(code,/^[A-HJ-NP-Z2-9]{12}$/);await assert.rejects(dispatch(state,'admin.generateCode',{},guest),e=>e.status===401);const {id}=await dispatch(state,'admin.saveAssessment',{...exam([{categoryId:c1.id,mode:'random',count:4}]),questionCount:4,code},admin);const catalog=await dispatch(state,'catalog',{},guest);const publicExam=catalog.assessments.find(a=>a.id===id);assert.equal(publicExam.accessCode,undefined);assert.equal(publicExam.blocks,undefined);assert.ok(!JSON.stringify(publicExam).includes(code));let data=await dispatch(state,'admin.data',{},admin);assert.equal(data.assessments.find(a=>a.id===id).accessCode,code);await dispatch(state,'admin.saveAssessment',{...data.assessments.find(a=>a.id===id),code:''},admin);data=await dispatch(state, 'admin.data',{},admin);assert.equal(data.assessments.find(a=>a.id===id).accessCode,code);const attempt=await dispatch(state,'attempt.start',{...admission(id),code},guest);assert.equal(attempt.attempt.questions.length,4);});
test('empty codex can be created before sections and important article flag persists',async()=>{const state=seed();const code=await dispatch(state,'admin.saveMaterial',{section:'legislation',title:'Новый кодекс',published:false},admin);const saved=await dispatch(state,'admin.saveMaterial',{...code,published:true,groups:[{title:'Раздел 1',articles:[{num:'1',title:'Важная статья',text:'Расшифровка',important:true}]}]},admin);const catalog=await dispatch(state,'catalog',{},guest);assert.equal(catalog.materials.find(m=>m.id===saved.id).groups[0].articles[0].important,true);});
test('hierarchy ranks and certificate formats are enforced server-side',async()=>{const state=seed();const org={director:{name:'Начальник',rank:'Генерал-майор',certificate:'100-001'},deputies:[{name:'Заместитель',rank:'Рядовой'}],departments:[{name:'УСБ',head:{rank:'Рядовой'},deputies:[{rank:'Рядовой'}],subdivisions:[{name:'Отдел',head:{rank:'Рядовой'},deputies:[{rank:''}]}]}],ranks:[]};const material=await dispatch(state,'admin.saveMaterial',{section:'structure',title:'Иерархия',organization:org},admin);const result=material.organization;assert.equal(result.deputies[0].rank,'Полковник');assert.equal(result.departments[0].head.rank,'Подполковник');assert.equal(result.departments[0].deputies[0].rank,'Майор');assert.equal(result.departments[0].subdivisions[0].head.rank,'Майор');assert.equal(result.departments[0].subdivisions[0].deputies[0].rank,'');org.director.certificate='100_001';await assert.rejects(dispatch(state,'admin.saveMaterial',{section:'structure',title:'Плохой формат',organization:org},admin),/123-456/);});
test('questions referenced by composition cannot silently move to another category or be deleted',async()=>{const {state,c1,c2}=await fixture();await dispatch(state,'admin.saveAssessment',{...exam([{categoryId:c1.id,mode:'random',count:4}]),questionCount:4},admin);const question=state.questions.find(q=>q.id==='koap1');await assert.rejects(dispatch(state,'admin.saveQuestion',{...question,categoryId:c2.id},admin),/Сначала уберите/);await assert.rejects(dispatch(state,'admin.delete',{collection:'questions',id:question.id},admin),/используется/);assert.equal(question.categoryId,c1.id);});
